version: '3.8'

services:
  db:
    image: postgres:13.7
    container_name: liquibase_database_migrations_db
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: liquibase_database_migrations_db
    volumes:
      - /var/lib/postgresql
    ports:
      - '5432:5432'